events {
    worker_connections 1024;
}

http {
    upstream backend {
        server backend:3005;
    }

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        # server_name aira.winnerx0.dev;
        server_name localhost;

        # Certbot webroot challenge
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # location / {
        #     return 301 https://$host$request_uri;
        # }

        location / {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # server {
    #     listen 443 ssl;
    #     server_name aira.winnerx0.dev;

    #     ssl_certificate     /etc/letsencrypt/live/aira.winnerx0.dev/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/aira.winnerx0.dev/privkey.pem;
    #     resolver 127.0.0.11 valid=10s;
    #     location / {
    #         proxy_pass http://backend/;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #     }
    # }
}
