worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        server aira_backend:3000;
    }

    server {

        listen 80;

        resolver 127.0.0.11 valid=10s;

        location / {
            proxy_pass http://backend/;
        
        }
    }
}