/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/memories': typeof MemoriesRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/memories': typeof MemoriesRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/memories': typeof MemoriesRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connections' | '/memories' | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connections' | '/memories' | '/workflows'
  id: '__root__' | '/' | '/connections' | '/memories' | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  MemoriesRoute: typeof MemoriesRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  MemoriesRoute: MemoriesRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
